name: 공부 일지 만들기

on:
  workflow_dispatch:

jobs:
  make-study-diary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Run main.py
        id: run_main
        run: echo "::set-output name=diary::$(python main.py)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 공부 일지
          body: ${{ steps.run_main.outputs.diary }}
