name: 공부 일지 만들기

on:
  workflow_dispatch:

jobs:
  make-study-diary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Run main.py
        run: python main.py
